INSERT INTO `gelars`(`singkatan`,`gelar`) VALUES
('S.P.','(S1) Sarjana Pertanian'),
('S.Pd.','(S1) Sarjana Pendidikan'),
('S.Pd.I.','(S1) Sarjana Pendidikan Islam'),
('S.Psi.','(S1) Sarjana Psikologi'),
('S.Pt.','(S1) Sarjana Peternakan'),
('S.E.','(S1) Sarjana Ekonomi'),
('S.Ag.','(S1) Sarjana Agama'),
('S.Fil.','(S1) Sarjana Filsafat'),
('S.Fil.I.','(S1) Sarjana Filsafat Islam'),
('S.H.','(S1) Sarjana Hukum'),
('S.H.I.','(S1) Sarjana Hukum Islam'),
('S.Hum.','(S1) Sarjana Humaniora'),
('S.I.P.','(S1) Sarjana Ilmu Politik'),
('S.Kar.','(S1) Sarjana Karawitan'),
('S.Ked.','(S1) Sarjana Kedokteran'),
('S.Kes.','(S1) Sarjana Kesehatan'),
('S.Kom.','(S1) Sarjana Komputer'),
('S.K.M.','(S1) Sarjana Kesehatan masyarakat'),
('S.S.','(S1) Sarjana Sastra'),
('S.Si.','(S1) Sarjana Sains'),
('S.Sn.','(S1) Sarjana Seni'),
('S.Sos.','(S1) Sarjana Sosial'),
('S.Sos.I.','(S1) Sarjana Sosial Islam'),
('S.T.','(S1) Sarjana Teknik'),
('S.Th.','(S1) Sarjana Theologi'),
('S.Th.I.','(S1) Sarjana Theologi Islam'),
('M.Ag.','(S2) Magister Agama'),
('M.E.','(S2) Magister Ekonomi'),
('M.E.I.','(S2) Magister Ekonomi Islam'),
('M.Fil.','(S2) Magister Filsafat'),
('M.Fil.I.','(S2) Magister Filsafat Islam'),
('M.H.','(S2) Magister Hukum'),
('M.Hum.','(S2) Magister Humaniora'),
('M.H.I.','(S2) Magister Hukum Islam'),
('M.Kes.','(S2) Magister Kesehatan'),
('M.Kom.','(S2) Magister Komputer'),
('M.M.','(S2) Magister Manajemen'),
('M.P.','(S2) Magister Pertanian'),
('M.Pd.','(S2) Magister Pendidikan'),
('M.Pd.I.','(S2) Magister Pendidikan Islam'),
('M.Psi.','(S2) Magister Psikologi'),
('M.Si.','(S2) Magister Sains'),
('M.Sn.','(S2) Magister Seni'),
('M.T.','(S2) Magister Teknik'),
('Dr.','(S3) Doktor'),
('A.P','(D1) Profesional Ahli Pratama'),
('A.Ma','(D2) Profesional Ahli Muda'),
('A.Md','(D3) Profesional Ahli Madya'),
('A.','(D4) Profesional Ahli')
